# Generated by Django 5.1 on 2024-09-15 14:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine_app', '0004_rename_solde_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_deposit_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
