# Generated by Django 5.1 on 2024-09-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine_app', '0005_account_last_deposit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'en cours'), ('done', 'valider')], default='pending', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Depot'), ('withdraw', 'Retrait')], default='deposit', max_length=10),
        ),
    ]
