# Generated by Django 5.1 on 2024-09-22 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tontine_app', '0006_transaction_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
    ]
