# Generated by Django 5.1 on 2024-09-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine_app', '0007_remove_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'en cours'), ('done', 'valider')], default='pending', max_length=10, null=True),
        ),
    ]
