# Generated by Django 5.1 on 2024-09-22 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tontine_app', '0008_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='last_deposit_date',
        ),
    ]
