# Generated by Django 5.1 on 2024-09-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine_app', '0010_alter_transaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
    ]
